#!/usr/bin/python3
# Atheris fuzz harness for pip's requirements-file parser.
#
# Feeds fuzzer-generated bytes through pip._internal.req.req_file.parse_requirements (the same
# code path pip uses to read a `requirements.txt`). The pip-under-test is imported from the
# in-tree source (/mayhem/src, set on PYTHONPATH by the native launcher) — no install needed,
# pip vendors its own dependencies under pip._vendor.
import os
import sys
import tempfile

import atheris

# Import pip from the checkout's source tree (the launcher sets PYTHONPATH=/mayhem/src; this
# fallback keeps the harness runnable directly, e.g. for reproduction).
sys.path.insert(0, "/mayhem/src")

_REQ_PATH = os.path.join(tempfile.gettempdir(), "fuzz_pip_requirements.txt")

# Pip is imported LAZILY (on the first fuzz iteration), not at module load. Importing
# pip._internal.network.session eagerly pulls in pip's whole vendored stack (requests, urllib3,
# packaging, …) and took ~8.7s — long enough that Mayhem's libFuzzer smoke test timed out while
# "printing options" (it runs the target with -help=1, which only reaches atheris.Setup after the
# module-level imports finish). Mayhem then declared the target non-running → 0 edges, even though
# it fuzzed for the full duration. Deferring the import lets Setup print options in <0.1s (smoke
# passes); the parser is still instrumented via instrument_imports(include=["pip._internal"]) on
# first use, so coverage is unaffected (~1.7k edges locally). We scope instrumentation to
# pip._internal so the vendored tree (pip._vendor.*) is loaded-but-not-instrumented — enough to
# cover the parser without paying to rewrite thousands of vendored modules.
_parse_requirements = None
_PipSession = None
_RequirementsFileParseError = None


def _ensure_loaded():
    global _parse_requirements, _PipSession, _RequirementsFileParseError
    if _parse_requirements is not None:
        return
    with atheris.instrument_imports(include=["pip._internal"]):
        import pip._internal.req.req_file as pipreq
        from pip._internal.exceptions import RequirementsFileParseError
        from pip._internal.network.session import PipSession
    _parse_requirements = pipreq.parse_requirements
    _PipSession = PipSession
    _RequirementsFileParseError = RequirementsFileParseError


@atheris.instrument_func
def TestOneInput(data):
    _ensure_loaded()
    # Mayhem mounts the image read-only, so scratch output must go to /tmp, never /mayhem.
    with open(_REQ_PATH, "wb") as fd:
        fd.write(data)
    try:
        for _ in _parse_requirements(
            _REQ_PATH,
            _PipSession(),
            finder=None,
            options=None,
            constraint=None,
        ):
            pass
    except UnicodeDecodeError:
        # A non-UTF-8 requirements file is a user-input issue, not a pip defect.
        pass
    except _RequirementsFileParseError:
        # The parser's own "this file is malformed" signal — expected, not a bug.
        pass


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
